#ifndef INVOKEPARSE_ERRORID_H
#define INVOKEPARSE_ERRORID_H


#define ERROR_LOG_PARSER_ROOT_NULL          -10
#define ERROR_LOG_PARSER_NO_APP_FROM_RI     -11
#define ERROR_LOG_PARSER_NO_FREENODE        -12


#endif //INVOKEPARSE_ERRORID_H
